apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
      - name: php
        image: webmaks/hphp-fpm:v3
        env:
        - name: "dbname"
          valueFrom:
            secretKeyRef:
              name: dbname
              key: dbname
        - name: "dbuser"
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbuser
        - name: "dbpass"
          valueFrom:
            secretKeyRef:
              name: dbpass
              key: dbpass

