apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hingress
  annotations:
    ingress.kubernates.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: happ
            servicePort: 1234
